default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("POSTGRESQL_HOST", "localhost") %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME", "postgres") %>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD", "") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DB_DEV", "my_todos_development") %>
  # ถ้าอยากใช้ URL สำหรับ dev ค่อยใส่บรรทัดนี้ (ไม่แนะนำถ้าใช้โลคัล)
  # url: <%= ENV["DATABASE_URL_DEVELOPMENT"] %>

# config/database.yml
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

  # ที่สำคัญ: อย่าใส่ url ใน test

production:
  primary: &primary_production
    <<: *default
    # ใช้ URL ของ Render เฉพาะ production
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production
  cable:
    <<: *primary_production
